defaults:
  - fe: defaults
  - rl: defaults
  - _self_

hydra:
  run:
    dir: logs/${basename}/${now:%Y%m%d-%H%M}

memory_size: 10000
nsteps: 100
position_random: False
posture_random: False
start_steps: 10000
total_steps: 500000
nevalepisodes: 5
update_after: 1000
update_every: 50
batch_size: 50
save_anim_num: 10
eval_num: 100
device: cuda
seed: 42
_replay_buffer:
  _target_: agents.buffer.ReplayBuffer
  memory_size: ${memory_size}

basename: SAC_trainedDCAE_o-${rl.obs_dim}_a-${rl.act_dim}

fe_with_init: True
