defaults:
  - fe: vae
  - _self_

hydra:
  run:
    dir: logs/${basename}/${now:%Y%m%d-%H%M}

basename: SB3_SAC_trainedVAE

_env:
  id: MZ04CableGrasp-v0
  render_mode: rgb_array
  max_episode_steps: ${nsteps}
  position_random: ${position_random}
  posture_random: ${posture_random}

_model:
  _target_: stable_baselines3.SAC
  policy: MlpPolicy
  verbose: 0

nsteps: 100
position_random: False
posture_random: False
fe_with_init: True
device: cuda
total_steps: 500000
seed: 42
nevalepisodes: 5
eval_num: 1000
