defaults:
  - fe: defaults
  - _self_

hydra:
  run:
    dir: logs/${basename}/${now:%Y%m%d-%H%M}

_env:
  id: MZ04CableGrasp-v0
  render_mode: rgb_array
  max_episode_steps: ${nsteps}
  position_random: ${position_random}
  posture_random: ${posture_random}

_model:
  _target_: agents.SAC.SAC
  gamma: 0.7
  lr: 1e-3

memory_size: 10000
nsteps: 100
position_random: False
posture_random: False
start_steps: 10000
total_steps: 500000
nevalepisodes: 5
update_after: 1000
update_every: 1
batch_size: 50
eval_num: 1000
device: cuda
seed: 42
_replay_buffer:
  _target_: agents.buffer.ReplayBuffer
  memory_size: ${memory_size}

basename: SAC_trainedDCAE

fe_with_init: True
