defaults:
  - fe: ../../fe/vae
  - _self_

hydra:
  run:
    dir: logs/${basename}/${now:%Y%m%d-%H%M}

basename: FE_CycleGAN_VAE

_model:
  _target_: agents.CycleGAN.FeatureExtractionCycleGAN

real_data_path: real_rgbd_random.npy

log_name: grasp_rgbd
position_random: False
posture_random: False
fe_with_init: True
data_size: 10000

nepochs: 300
es_patience: 10
batch_size: 64

device: cuda
seed: 42

save_recimg_num: 10
