defaults:
  - fe: ../../fe/defaults
  - _self_

hydra:
  run:
    dir: logs/${basename}/${now:%Y%m%d-%H%M}

_env:
  id: MZ04CableGrasp-v0
  render_mode: rgb_array
  max_episode_steps: ${nsteps}
  position_random: ${position_random}
  posture_random: ${posture_random}

basename: DCAE
log_name: grasp_rgbd

nsteps: 100
position_random: False
posture_random: False

batch_size: 128
nepochs: 1000
es_patience: 100

device: cuda
seed: 42

gathering_data: True
with_init: False
data_size: 10000

save_recimg_num: 10
