lr: 1e-3
img_width: 108
img_height: 72
img_dim: 4
hidden_dim: 20
_trans:
  _target_: agents.utils.MyTrans
_net_activation:
  _target_: torch.nn.GELU
_loss_func:
  _target_: agents.utils.SSIMLoss
model_name: DCAE_gelu_ssim_w-init.pth
